version: "3.7"

services:
  backend:
    build: .
    command: >
      sh -c "npx prisma migrate dev && npm run watch"
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - db
    networks:
      - backend
  
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: readaily_dev
    networks:
      - backend
  
networks:
  backend: