version: "3.7"

services:
  backend:
    image: katsudevelopers:readaily-backend:$docker_image_tag
    command: >
      sh -c "npx prisma db push && npm run server"
    ports:
      - "8082:8080"
    depends_on:
      - db
    network:
      - readaily_backend
    env_file: .env

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: readaily_dev
    networks:
      - readaily_backend

networks:
  backend: